---
# https://github.com/adrienverge/yamllint
# https://yamllint.readthedocs.io/en/stable/configuration.html DOCS

extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 80
    level: warning
#   # don't bother me with this rule
#   indentation: disable
