---
name: build-pipeline

on:
  push:
    branches:
      - master
      - feature/pre-commit

  pull_request:
    branches:
      - master
    types: opened

jobs:

  read-secrets:
    uses: ./.github/workflows/read-secrets.yml
    with:
      secrets_path: ./secrets.yaml
    secrets:
      git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}

  set-env-secrets:
    needs: read-secrets
    runs-on: ubuntu-latest
    outputs:
      MAIL_FROM: ${{ steps.set_env.outputs.MAIL_FROM }}
      MAIL_TO: ${{ steps.set_env.outputs.MAIL_TO }}
      SMTP_USERNAME: ${{ steps.set_env.outputs.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ steps.set_env.outputs.SMTP_PASSWORD }}
    steps:
      - name: Read environment variables with jq and define them
        id: set_env
        run: |
          json_secret='${{ needs.read-secrets.outputs.secrets }}'
          echo "MAIL_FROM=$(echo "$json_secret" | jq -r '.MAIL_FROM')" >> $GITHUB_OUTPUT
          echo "MAIL_TO=$(echo "$json_secret" | jq -r '.MAIL_TO')" >> $GITHUB_OUTPUT
          echo "SMTP_USERNAME=$(echo "$json_secret" | jq -r '.SMTP_USERNAME')" >> $GITHUB_OUTPUT
          echo "SMTP_PASSWORD=$(echo "$json_secret" | jq -r '.SMTP_PASSWORD')" >> $GITHUB_OUTPUT

  push-trigger:
    needs: set-env-secrets
    uses: ./.github/workflows/build-workflow.yml
    with:
      registry: ghcr.io
      smtp_address: smtp.gmail.com
      smtp_port: 587
    secrets:
      MAIL_FROM: ${{ needs.set-env-secrets.outputs.MAIL_FROM }}
      MAIL_TO: ${{ needs.set-env-secrets.outputs.MAIL_TO }}
      SMTP_USERNAME: ${{ needs.set-env-secrets.outputs.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ needs.set-env-secrets.outputs.SMTP_PASSWORD }}
