---
name: build-pipeline

on:
  push:
    branches: [ci-feature, master]
  pull_request:
    branches: [master]
    types: opened

jobs:
  push-trigger:
    uses: ./.github/workflows/build-workflow.yml
    with:
      ghub_repository: amexei/angular-react-starter
      registry: ghcr.io
      smtp_address: smtp.gmail.com
      smtp_port: 587
    secrets:
      mail_from: ${{ secrets.MAIL_FROM }}
      mail_to: ${{ secrets.MAIL_TO }}
      smtp_password: ${{ secrets.SMTP_PASSWORD }}
      smtp_username: ${{ secrets.SMTP_USERNAME }}
